"""AI executive briefing panel with session-state persistence."""

import streamlit as st

from anomaly_detection.models import Anomaly


def render(kpi: dict, anomalies: list[Anomaly]) -> None:
    st.subheader("AI Executive Briefing")
    st.caption("Generated by Claude — PeregrineOps Intelligence Engine")

    if st.button("Regenerate Briefing", type="primary"):
        st.session_state.pop("briefing_text", None)

    if "briefing_text" not in st.session_state:
        with st.spinner("Generating briefing via Claude…"):
            try:
                import sys
                from pathlib import Path
                sys.path.insert(0, str(Path(__file__).parent.parent.parent))
                from briefing_engine import BriefingGenerator
                gen = BriefingGenerator()
                st.session_state["briefing_text"] = gen.generate(kpi, anomalies)
            except Exception as exc:
                st.session_state["briefing_text"] = (
                    f"Briefing unavailable: {exc}\n\n"
                    "Check that ANTHROPIC_API_KEY is set in your .env file."
                )

    briefing_text = st.session_state.get("briefing_text", "")
    paragraphs = [p.strip() for p in briefing_text.split("\n\n") if p.strip()]

    labels = ["Current Situation", "Anomalies & Risk Assessment", "Recommended Actions"]
    for i, para in enumerate(paragraphs):
        label = labels[i] if i < len(labels) else f"Section {i + 1}"
        st.markdown(
            f"""
            <div style="
                background-color: #1c1f26;
                border-left: 4px solid #4a90d9;
                padding: 16px 20px;
                margin-bottom: 12px;
                border-radius: 4px;
            ">
                <p style="color:#8ab4f8; font-size:11px; font-weight:600;
                          letter-spacing:1px; margin-bottom:8px; text-transform:uppercase;">
                    {label}
                </p>
                <p style="color:#e8eaed; font-size:15px; line-height:1.6; margin:0;">
                    {para}
                </p>
            </div>
            """,
            unsafe_allow_html=True,
        )
